from typing import NamedTuple, Callable, List, Dict
from BaseClasses import CollectionState

from .Constants import *


class BKRegionData(NamedTuple):
    connecting_regions: List[str] = []


region_data_table: Dict[str, BKRegionData] = {
    RGN_MENU: BKRegionData([RGN_SPIRAL_MOUNTAIN]),
    RGN_SPIRAL_MOUNTAIN: BKRegionData([RGN_GRUNTILDAS_LAIR_LOBBY]),
    RGN_GRUNTILDAS_LAIR_LOBBY: BKRegionData([RGN_MUMBOS_MOUNTAIN, RGN_GRUNTILDAS_LAIR_50_NOTE_DOOR]),
    RGN_GRUNTILDAS_LAIR_50_NOTE_DOOR: BKRegionData([RGN_TREASURE_TROVE_COVE, RGN_CLANKERS_CAVERN, RGN_GRUNTILDAS_LAIR_180_NOTE_DOOR]),
    RGN_MUMBOS_MOUNTAIN: BKRegionData([]),
    RGN_TREASURE_TROVE_COVE: BKRegionData([]),
    RGN_CLANKERS_CAVERN: BKRegionData([]),
    RGN_GRUNTILDAS_LAIR_180_NOTE_DOOR: BKRegionData([RGN_BUBBLEGLOOP_SWAMP, RGN_GRUNTILDAS_LAIR_260_NOTE_DOOR]),
    RGN_BUBBLEGLOOP_SWAMP: BKRegionData([]),
    RGN_GRUNTILDAS_LAIR_260_NOTE_DOOR: BKRegionData([RGN_FREEZEEZY_PEAK, RGN_GOBIS_VALLEY, RGN_GRUNTILDAS_LAIR_350_NOTE_DOOR]),
    RGN_FREEZEEZY_PEAK: BKRegionData([]),
    RGN_GOBIS_VALLEY: BKRegionData([]),
    RGN_GRUNTILDAS_LAIR_350_NOTE_DOOR: BKRegionData([RGN_MAD_MONSTER_MANSION, RGN_GRUNTILDAS_LAIR_450_NOTE_DOOR]),
    RGN_MAD_MONSTER_MANSION: BKRegionData([]),
    RGN_GRUNTILDAS_LAIR_450_NOTE_DOOR: BKRegionData([RGN_RUSTY_BUCKET_BAY, RGN_GRUNTILDAS_LAIR_640_NOTE_DOOR]),
    RGN_RUSTY_BUCKET_BAY: BKRegionData([]),
    RGN_GRUNTILDAS_LAIR_640_NOTE_DOOR: BKRegionData([RGN_CLICK_CLOCK_WOOD, RGN_GRUNTILDAS_LAIR_765_NOTE_DOOR]),
    RGN_CLICK_CLOCK_WOOD: BKRegionData([]),
    RGN_GRUNTILDAS_LAIR_765_NOTE_DOOR: BKRegionData([RGN_GRUNTILDAS_LAIR_FURNACE_FUN]),
    RGN_GRUNTILDAS_LAIR_FURNACE_FUN: BKRegionData([RGN_GRUNTILDAS_LAIR_810_NOTE_DOOR]),
    RGN_GRUNTILDAS_LAIR_810_NOTE_DOOR: BKRegionData([RGN_GRUNTILDAS_LAIR_882_NOTE_DOOR]),
    RGN_GRUNTILDAS_LAIR_882_NOTE_DOOR: BKRegionData([RGN_GRUNTILDAS_LAIR_FIGHT]),
    RGN_GRUNTILDAS_LAIR_FIGHT: BKRegionData([])
}

def get_exit(region, exit_name):
    for exit in region.exits:
        if exit.connected_region.name == exit_name:
            return exit
